In [1]:
import random

import numpy as np
import random
import keras
from sklearn.preprocessing import StandardScaler
import tensorflow as tf
from keras import models
from keras import layers

%matplotlib inline

Using TensorFlow backend.


In [2]:
# number of characters in a word.
# for instance abccba has nb_chars = 6
nb_chars = 4

# number of possible characters used during the encoding.
# for instance abcde leads to 01234 has nb_letters = 5
#nb_letters = 10
nb_letters = 26

# number of words samples to be generated for the training
nb_words = 3000

In [3]:
# total number of combinations
nb_letters**nb_chars

456976

In [4]:
def create_inputs(nb_words, nb_chars, nb_letters):
    '''Create a numpy array of nb_words rows with nb_chars columns each element
    being a random letter of nb_letters (a, b...)'''
    words = np.zeros((nb_words, nb_chars), dtype=int)
    for w in range(nb_words):
        for c in range(nb_chars):
            i = random.randint(0, nb_letters-1)
            words[w, c] = ord('a') + i
    return words


def encrypt(words, nb_words, nb_chars):
    '''Encrypt each element of a numpy array of nb_words rows with nb_chars 
    columns each item with a secret algorithm'''
    
    encrypted_words = words.copy()
    encrypted_words_probs = np.zeros((nb_words, nb_chars, nb_chars))
    
    #val_max = -1
    
    for w in range(nb_words):
        for c in range(nb_chars): # 0,1,2,3,4
            encrypted_words[w,c] = int(words[w,c]) - 49
            val = encrypted_words[w,c] - 48
            
            #if val > val_max:
            #    val_max = val
            
            # add entropy (i.e. mistakes in the encryption)
            #epsilon = random.randint(0, 100)
            #if epsilon == 5 and val != val_max:
            #val +=1
            
            #print('w:',w,', c:',c,', [wc]:', val)
            #encrypted_words_probs[w, c, val ] = 1.0
            encrypted_words[w,c] = val
    return encrypted_words

def print_output(words, nb_words, nb_chars):
    for w in range(nb_words):
        word = ''
        for c in range(nb_chars):
            word += chr(words[w,c])
        print(word)


In [5]:
nb_features = nb_chars

# This returns a tensor
inputs = layers.Input(shape=(nb_chars,), dtype='float32', name='main_input')

# a layer instance is callable on a tensor, and returns a tensor
x = layers.Dense(2048, activation='relu', name='hl_1')(inputs)
#x = layers.Dense(64, activation='relu', name='hl_2')(x)

outputs = []
losses = {}
for o in range(nb_chars):
    name_i = 'output_'+str(o)
    output_i = layers.Dense(nb_letters, activation='softmax', dtype='float32', name=name_i)(x)
    outputs.append(output_i)
    losses[name_i] = 'categorical_crossentropy'

model = keras.models.Model(inputs=inputs, outputs=outputs)

model.compile(optimizer='rmsprop',
              loss=losses,
              metrics=['accuracy'])       

In [6]:
print(model.summary())

__________________________________________________________________________________________________
Layer (type)                    Output Shape         Param #     Connected to                     
main_input (InputLayer)         (None, 4)            0                                            
__________________________________________________________________________________________________
hl_1 (Dense)                    (None, 2048)         10240       main_input[0][0]                 
__________________________________________________________________________________________________
output_0 (Dense)                (None, 26)           53274       hl_1[0][0]                       
__________________________________________________________________________________________________
output_1 (Dense)                (None, 26)           53274       hl_1[0][0]                       
__________________________________________________________________________________________________
output_2 (

In [7]:
def display_x(x):
    words = []
    for w in x:
        word = ''
        for c in w:
            word += chr(c)
        words.append(word)
   
    print(words)

In [8]:
# ALL IN ONE STEP ('OSSIFIED')

x = create_inputs(nb_words, nb_chars, nb_letters)
display_x(x[:3])
print('x:\n', x[:3], 'out of ',len(x))
print()

# process the x data as useful ANN input data
scaler = StandardScaler()
x_train  = scaler.fit_transform(x)

print('x_train:\n', x_train[:3], 'out of ',len(x_train))
print()

# create output data for training
y = encrypt(x, nb_words, nb_chars)
print('y:\n', y)
print()
# process the y data as useful ANN output data
y_train = keras.utils.to_categorical(y, nb_letters)
print('y_train:\n', y_train[:3], 'out of ',len(y_train))

['tthk', 'ytrn', 'bhff']
x:
 [[116 116 104 107]
 [121 116 114 110]
 [ 98 104 102 102]] out of  3000

x_train:
 [[ 0.86440601  0.88369598 -0.75328185 -0.33426616]
 [ 1.54397048  0.88369598  0.58556852  0.07210902]
 [-1.58202609 -0.70030399 -1.02105192 -1.01155812]] out of  3000

y:
 [[19 19  7 10]
 [24 19 17 13]
 [ 1  7  5  5]
 ...
 [ 7  7  1 13]
 [ 3  0  9  3]
 [ 9  9  5 11]]

y_train:
 [[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0.
   0. 0. 0.]
  [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0.
   0. 0. 0.]
  [0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
   0. 0. 0.]
  [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
   0. 0. 0.]]

 [[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
   0. 1. 0.]
  [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0.
   0. 0. 0.]
  [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0.
   0. 0. 0.]
  [0. 0. 0. 0

/usr/local/lib/python3.6/dist-packages/sklearn/utils/validation.py:595: DataConversionWarning: Data with input dtype int64 was converted to float64 by StandardScaler.
  warnings.warn(msg, DataConversionWarning)
/usr/local/lib/python3.6/dist-packages/sklearn/utils/validation.py:595: DataConversionWarning: Data with input dtype int64 was converted to float64 by StandardScaler.
  warnings.warn(msg, DataConversionWarning)


In [9]:
def get_sub_sub_set(y, c_ref, nb_chars):
    '''Retrieve the probalities of the i-th char'''
    nb_samples = len(y)
    
    yi = np.zeros((nb_samples, nb_letters), dtype=int)
    
    for s in range(nb_samples):
        for c in range(nb_chars):
            #print('ysl:',y[s][0][l_i])
            if c == c_ref:
                yi[s] = y[s, c]
                
    return yi

In [10]:
y_train2 = []
for c in range(nb_chars):
    yi_train = get_sub_sub_set(y_train, c, nb_chars)
    y_train2.append(yi_train)

In [11]:
y_train2[:3]

[array([[0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 1, 0],
        [0, 1, 0, ..., 0, 0, 0],
        ...,
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0]]), array([[0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        ...,
        [0, 0, 0, ..., 0, 0, 0],
        [1, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0]]), array([[0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        ...,
        [0, 1, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0]])]

In [12]:
history = model.fit(x_train, y_train2, epochs=1000, batch_size=100,  verbose=1)

Epoch 1/1000
3000/3000 [==============================] - 0s 162us/step - loss: 11.6812 - output_0_loss: 2.9314 - output_1_loss: 2.9190 - output_2_loss: 2.9127 - output_3_loss: 2.9180 - output_0_acc: 0.1117 - output_1_acc: 0.0940 - output_2_acc: 0.1050 - output_3_acc: 0.0980
Epoch 2/1000
3000/3000 [==============================] - 0s 45us/step - loss: 10.2502 - output_0_loss: 2.5764 - output_1_loss: 2.5631 - output_2_loss: 2.5578 - output_3_loss: 2.5529 - output_0_acc: 0.1630 - output_1_acc: 0.1557 - output_2_acc: 0.1620 - output_3_acc: 0.1727
Epoch 3/1000
3000/3000 [==============================] - 0s 44us/step - loss: 9.5225 - output_0_loss: 2.3925 - output_1_loss: 2.3812 - output_2_loss: 2.3787 - output_3_loss: 2.3702 - output_0_acc: 0.2033 - output_1_acc: 0.1890 - output_2_acc: 0.1993 - output_3_acc: 0.1963
Epoch 4/1000
3000/3000 [==============================] - 0s 46us/step - loss: 9.0244 - output_0_loss: 2.2675 - output_1_loss: 2.2557 - output_2_loss: 2.2539 - output_3_loss: 

3000/3000 [==============================] - 0s 40us/step - loss: 5.3651 - output_0_loss: 1.3530 - output_1_loss: 1.3495 - output_2_loss: 1.3397 - output_3_loss: 1.3228 - output_0_acc: 0.4837 - output_1_acc: 0.4680 - output_2_acc: 0.4793 - output_3_acc: 0.4840
Epoch 31/1000
3000/3000 [==============================] - 0s 39us/step - loss: 5.3221 - output_0_loss: 1.3460 - output_1_loss: 1.3415 - output_2_loss: 1.3329 - output_3_loss: 1.3017 - output_0_acc: 0.4717 - output_1_acc: 0.4743 - output_2_acc: 0.4663 - output_3_acc: 0.4860
Epoch 32/1000
3000/3000 [==============================] - 0s 40us/step - loss: 5.2363 - output_0_loss: 1.3254 - output_1_loss: 1.3121 - output_2_loss: 1.3140 - output_3_loss: 1.2847 - output_0_acc: 0.4927 - output_1_acc: 0.4793 - output_2_acc: 0.4953 - output_3_acc: 0.5137
Epoch 33/1000
3000/3000 [==============================] - 0s 41us/step - loss: 5.1639 - output_0_loss: 1.3004 - output_1_loss: 1.2973 - output_2_loss: 1.3019 - output_3_loss: 1.2643 - outp

3000/3000 [==============================] - 0s 39us/step - loss: 3.8775 - output_0_loss: 0.9865 - output_1_loss: 0.9882 - output_2_loss: 0.9704 - output_3_loss: 0.9325 - output_0_acc: 0.6150 - output_1_acc: 0.6330 - output_2_acc: 0.6427 - output_3_acc: 0.6507
Epoch 60/1000
3000/3000 [==============================] - 0s 39us/step - loss: 3.8477 - output_0_loss: 0.9759 - output_1_loss: 0.9735 - output_2_loss: 0.9668 - output_3_loss: 0.9316 - output_0_acc: 0.6350 - output_1_acc: 0.6300 - output_2_acc: 0.6383 - output_3_acc: 0.6603
Epoch 61/1000
3000/3000 [==============================] - 0s 38us/step - loss: 3.7833 - output_0_loss: 0.9717 - output_1_loss: 0.9476 - output_2_loss: 0.9413 - output_3_loss: 0.9227 - output_0_acc: 0.6267 - output_1_acc: 0.6550 - output_2_acc: 0.6453 - output_3_acc: 0.6643
Epoch 62/1000
3000/3000 [==============================] - 0s 39us/step - loss: 3.7681 - output_0_loss: 0.9586 - output_1_loss: 0.9548 - output_2_loss: 0.9381 - output_3_loss: 0.9167 - outp

3000/3000 [==============================] - 0s 41us/step - loss: 2.9483 - output_0_loss: 0.7509 - output_1_loss: 0.7370 - output_2_loss: 0.7526 - output_3_loss: 0.7079 - output_0_acc: 0.7283 - output_1_acc: 0.7417 - output_2_acc: 0.7333 - output_3_acc: 0.7593
Epoch 89/1000
3000/3000 [==============================] - 0s 41us/step - loss: 2.9550 - output_0_loss: 0.7486 - output_1_loss: 0.7473 - output_2_loss: 0.7418 - output_3_loss: 0.7173 - output_0_acc: 0.7303 - output_1_acc: 0.7297 - output_2_acc: 0.7300 - output_3_acc: 0.7477
Epoch 90/1000
3000/3000 [==============================] - 0s 43us/step - loss: 2.9241 - output_0_loss: 0.7556 - output_1_loss: 0.7401 - output_2_loss: 0.7438 - output_3_loss: 0.6846 - output_0_acc: 0.7173 - output_1_acc: 0.7340 - output_2_acc: 0.7343 - output_3_acc: 0.7687
Epoch 91/1000
3000/3000 [==============================] - 0s 40us/step - loss: 2.8841 - output_0_loss: 0.7404 - output_1_loss: 0.7355 - output_2_loss: 0.7251 - output_3_loss: 0.6832 - outp

3000/3000 [==============================] - 0s 39us/step - loss: 2.3164 - output_0_loss: 0.6049 - output_1_loss: 0.5986 - output_2_loss: 0.5678 - output_3_loss: 0.5452 - output_0_acc: 0.8027 - output_1_acc: 0.7930 - output_2_acc: 0.8237 - output_3_acc: 0.8397
Epoch 118/1000
3000/3000 [==============================] - 0s 43us/step - loss: 2.3201 - output_0_loss: 0.6051 - output_1_loss: 0.5918 - output_2_loss: 0.5859 - output_3_loss: 0.5373 - output_0_acc: 0.7997 - output_1_acc: 0.8143 - output_2_acc: 0.8200 - output_3_acc: 0.8377
Epoch 119/1000
3000/3000 [==============================] - 0s 42us/step - loss: 2.2872 - output_0_loss: 0.5931 - output_1_loss: 0.5893 - output_2_loss: 0.5715 - output_3_loss: 0.5334 - output_0_acc: 0.8097 - output_1_acc: 0.8130 - output_2_acc: 0.8190 - output_3_acc: 0.8483
Epoch 120/1000
3000/3000 [==============================] - 0s 41us/step - loss: 2.2779 - output_0_loss: 0.5885 - output_1_loss: 0.5849 - output_2_loss: 0.5777 - output_3_loss: 0.5269 - o

3000/3000 [==============================] - 0s 42us/step - loss: 1.7973 - output_0_loss: 0.4703 - output_1_loss: 0.4689 - output_2_loss: 0.4536 - output_3_loss: 0.4045 - output_0_acc: 0.8673 - output_1_acc: 0.8727 - output_2_acc: 0.8790 - output_3_acc: 0.9017
Epoch 147/1000
3000/3000 [==============================] - 0s 42us/step - loss: 1.7757 - output_0_loss: 0.4718 - output_1_loss: 0.4590 - output_2_loss: 0.4409 - output_3_loss: 0.4040 - output_0_acc: 0.8647 - output_1_acc: 0.8687 - output_2_acc: 0.8807 - output_3_acc: 0.9033
Epoch 148/1000
3000/3000 [==============================] - 0s 40us/step - loss: 1.7811 - output_0_loss: 0.4684 - output_1_loss: 0.4543 - output_2_loss: 0.4582 - output_3_loss: 0.4002 - output_0_acc: 0.8657 - output_1_acc: 0.8727 - output_2_acc: 0.8677 - output_3_acc: 0.9053
Epoch 149/1000
3000/3000 [==============================] - 0s 40us/step - loss: 1.7553 - output_0_loss: 0.4573 - output_1_loss: 0.4558 - output_2_loss: 0.4430 - output_3_loss: 0.3993 - o

3000/3000 [==============================] - 0s 44us/step - loss: 1.4103 - output_0_loss: 0.3711 - output_1_loss: 0.3726 - output_2_loss: 0.3505 - output_3_loss: 0.3161 - output_0_acc: 0.9097 - output_1_acc: 0.9060 - output_2_acc: 0.9147 - output_3_acc: 0.9293
Epoch 176/1000
3000/3000 [==============================] - 0s 46us/step - loss: 1.3852 - output_0_loss: 0.3771 - output_1_loss: 0.3670 - output_2_loss: 0.3563 - output_3_loss: 0.2848 - output_0_acc: 0.9100 - output_1_acc: 0.9140 - output_2_acc: 0.9123 - output_3_acc: 0.9547
Epoch 177/1000
3000/3000 [==============================] - 0s 43us/step - loss: 1.3972 - output_0_loss: 0.3737 - output_1_loss: 0.3580 - output_2_loss: 0.3536 - output_3_loss: 0.3118 - output_0_acc: 0.9083 - output_1_acc: 0.9153 - output_2_acc: 0.9167 - output_3_acc: 0.9323
Epoch 178/1000
3000/3000 [==============================] - 0s 43us/step - loss: 1.3936 - output_0_loss: 0.3700 - output_1_loss: 0.3680 - output_2_loss: 0.3469 - output_3_loss: 0.3087 - o

3000/3000 [==============================] - 0s 39us/step - loss: 1.0966 - output_0_loss: 0.2913 - output_1_loss: 0.3000 - output_2_loss: 0.2751 - output_3_loss: 0.2302 - output_0_acc: 0.9410 - output_1_acc: 0.9263 - output_2_acc: 0.9440 - output_3_acc: 0.9620
Epoch 205/1000
3000/3000 [==============================] - 0s 39us/step - loss: 1.0846 - output_0_loss: 0.2890 - output_1_loss: 0.2806 - output_2_loss: 0.2734 - output_3_loss: 0.2415 - output_0_acc: 0.9380 - output_1_acc: 0.9507 - output_2_acc: 0.9480 - output_3_acc: 0.9560
Epoch 206/1000
3000/3000 [==============================] - 0s 40us/step - loss: 1.0548 - output_0_loss: 0.2835 - output_1_loss: 0.2851 - output_2_loss: 0.2656 - output_3_loss: 0.2205 - output_0_acc: 0.9427 - output_1_acc: 0.9430 - output_2_acc: 0.9567 - output_3_acc: 0.9623
Epoch 207/1000
3000/3000 [==============================] - 0s 41us/step - loss: 1.0668 - output_0_loss: 0.2872 - output_1_loss: 0.2792 - output_2_loss: 0.2714 - output_3_loss: 0.2291 - o

3000/3000 [==============================] - 0s 44us/step - loss: 0.8446 - output_0_loss: 0.2319 - output_1_loss: 0.2208 - output_2_loss: 0.2113 - output_3_loss: 0.1805 - output_0_acc: 0.9613 - output_1_acc: 0.9670 - output_2_acc: 0.9707 - output_3_acc: 0.9740
Epoch 234/1000
3000/3000 [==============================] - 0s 42us/step - loss: 0.8458 - output_0_loss: 0.2252 - output_1_loss: 0.2318 - output_2_loss: 0.2104 - output_3_loss: 0.1784 - output_0_acc: 0.9580 - output_1_acc: 0.9600 - output_2_acc: 0.9697 - output_3_acc: 0.9757
Epoch 235/1000
3000/3000 [==============================] - 0s 41us/step - loss: 0.8128 - output_0_loss: 0.2229 - output_1_loss: 0.2193 - output_2_loss: 0.1898 - output_3_loss: 0.1808 - output_0_acc: 0.9627 - output_1_acc: 0.9640 - output_2_acc: 0.9760 - output_3_acc: 0.9683
Epoch 236/1000
3000/3000 [==============================] - 0s 42us/step - loss: 0.8093 - output_0_loss: 0.2095 - output_1_loss: 0.2288 - output_2_loss: 0.2043 - output_3_loss: 0.1667 - o

3000/3000 [==============================] - 0s 44us/step - loss: 0.6449 - output_0_loss: 0.1726 - output_1_loss: 0.1760 - output_2_loss: 0.1639 - output_3_loss: 0.1323 - output_0_acc: 0.9790 - output_1_acc: 0.9810 - output_2_acc: 0.9763 - output_3_acc: 0.9830
Epoch 263/1000
3000/3000 [==============================] - 0s 43us/step - loss: 0.6258 - output_0_loss: 0.1680 - output_1_loss: 0.1735 - output_2_loss: 0.1578 - output_3_loss: 0.1266 - output_0_acc: 0.9817 - output_1_acc: 0.9783 - output_2_acc: 0.9797 - output_3_acc: 0.9877
Epoch 264/1000
3000/3000 [==============================] - 0s 43us/step - loss: 0.6394 - output_0_loss: 0.1746 - output_1_loss: 0.1702 - output_2_loss: 0.1565 - output_3_loss: 0.1380 - output_0_acc: 0.9747 - output_1_acc: 0.9763 - output_2_acc: 0.9800 - output_3_acc: 0.9793
Epoch 265/1000
3000/3000 [==============================] - 0s 43us/step - loss: 0.6206 - output_0_loss: 0.1668 - output_1_loss: 0.1669 - output_2_loss: 0.1626 - output_3_loss: 0.1244 - o

3000/3000 [==============================] - 0s 42us/step - loss: 0.4798 - output_0_loss: 0.1301 - output_1_loss: 0.1288 - output_2_loss: 0.1242 - output_3_loss: 0.0966 - output_0_acc: 0.9837 - output_1_acc: 0.9867 - output_2_acc: 0.9843 - output_3_acc: 0.9937
Epoch 292/1000
3000/3000 [==============================] - 0s 42us/step - loss: 0.4892 - output_0_loss: 0.1292 - output_1_loss: 0.1298 - output_2_loss: 0.1231 - output_3_loss: 0.1071 - output_0_acc: 0.9857 - output_1_acc: 0.9897 - output_2_acc: 0.9830 - output_3_acc: 0.9883
Epoch 293/1000
3000/3000 [==============================] - 0s 44us/step - loss: 0.4664 - output_0_loss: 0.1187 - output_1_loss: 0.1390 - output_2_loss: 0.1110 - output_3_loss: 0.0977 - output_0_acc: 0.9900 - output_1_acc: 0.9793 - output_2_acc: 0.9937 - output_3_acc: 0.9910
Epoch 294/1000
3000/3000 [==============================] - 0s 40us/step - loss: 0.4582 - output_0_loss: 0.1335 - output_1_loss: 0.1227 - output_2_loss: 0.1092 - output_3_loss: 0.0929 - o

3000/3000 [==============================] - 0s 45us/step - loss: 0.3614 - output_0_loss: 0.0983 - output_1_loss: 0.1012 - output_2_loss: 0.0829 - output_3_loss: 0.0790 - output_0_acc: 0.9887 - output_1_acc: 0.9910 - output_2_acc: 0.9940 - output_3_acc: 0.9887
Epoch 321/1000
3000/3000 [==============================] - 0s 45us/step - loss: 0.3618 - output_0_loss: 0.0973 - output_1_loss: 0.0991 - output_2_loss: 0.0972 - output_3_loss: 0.0682 - output_0_acc: 0.9893 - output_1_acc: 0.9900 - output_2_acc: 0.9880 - output_3_acc: 0.9963
Epoch 322/1000
3000/3000 [==============================] - 0s 45us/step - loss: 0.3484 - output_0_loss: 0.0930 - output_1_loss: 0.0983 - output_2_loss: 0.0832 - output_3_loss: 0.0739 - output_0_acc: 0.9883 - output_1_acc: 0.9917 - output_2_acc: 0.9913 - output_3_acc: 0.9927
Epoch 323/1000
3000/3000 [==============================] - 0s 43us/step - loss: 0.3492 - output_0_loss: 0.0943 - output_1_loss: 0.1020 - output_2_loss: 0.0810 - output_3_loss: 0.0719 - o

3000/3000 [==============================] - 0s 42us/step - loss: 0.2784 - output_0_loss: 0.0703 - output_1_loss: 0.0776 - output_2_loss: 0.0726 - output_3_loss: 0.0579 - output_0_acc: 0.9943 - output_1_acc: 0.9923 - output_2_acc: 0.9910 - output_3_acc: 0.9920
Epoch 350/1000
3000/3000 [==============================] - 0s 43us/step - loss: 0.2624 - output_0_loss: 0.0742 - output_1_loss: 0.0742 - output_2_loss: 0.0612 - output_3_loss: 0.0528 - output_0_acc: 0.9930 - output_1_acc: 0.9970 - output_2_acc: 0.9953 - output_3_acc: 0.9960
Epoch 351/1000
3000/3000 [==============================] - 0s 46us/step - loss: 0.2655 - output_0_loss: 0.0730 - output_1_loss: 0.0739 - output_2_loss: 0.0658 - output_3_loss: 0.0528 - output_0_acc: 0.9950 - output_1_acc: 0.9933 - output_2_acc: 0.9947 - output_3_acc: 0.9953
Epoch 352/1000
3000/3000 [==============================] - 0s 45us/step - loss: 0.2640 - output_0_loss: 0.0643 - output_1_loss: 0.0741 - output_2_loss: 0.0654 - output_3_loss: 0.0602 - o

3000/3000 [==============================] - 0s 41us/step - loss: 0.2027 - output_0_loss: 0.0559 - output_1_loss: 0.0596 - output_2_loss: 0.0435 - output_3_loss: 0.0437 - output_0_acc: 0.9967 - output_1_acc: 0.9950 - output_2_acc: 0.9990 - output_3_acc: 0.9953
Epoch 379/1000
3000/3000 [==============================] - 0s 42us/step - loss: 0.2014 - output_0_loss: 0.0536 - output_1_loss: 0.0546 - output_2_loss: 0.0526 - output_3_loss: 0.0407 - output_0_acc: 0.9963 - output_1_acc: 0.9950 - output_2_acc: 0.9963 - output_3_acc: 0.9967
Epoch 380/1000
3000/3000 [==============================] - 0s 41us/step - loss: 0.2013 - output_0_loss: 0.0559 - output_1_loss: 0.0532 - output_2_loss: 0.0498 - output_3_loss: 0.0424 - output_0_acc: 0.9963 - output_1_acc: 0.9963 - output_2_acc: 0.9960 - output_3_acc: 0.9970
Epoch 381/1000
3000/3000 [==============================] - 0s 41us/step - loss: 0.1958 - output_0_loss: 0.0537 - output_1_loss: 0.0559 - output_2_loss: 0.0483 - output_3_loss: 0.0379 - o

3000/3000 [==============================] - 0s 43us/step - loss: 0.1635 - output_0_loss: 0.0440 - output_1_loss: 0.0484 - output_2_loss: 0.0382 - output_3_loss: 0.0328 - output_0_acc: 0.9953 - output_1_acc: 0.9967 - output_2_acc: 0.9980 - output_3_acc: 0.9970
Epoch 408/1000
3000/3000 [==============================] - 0s 43us/step - loss: 0.1496 - output_0_loss: 0.0384 - output_1_loss: 0.0399 - output_2_loss: 0.0344 - output_3_loss: 0.0368 - output_0_acc: 0.9983 - output_1_acc: 0.9980 - output_2_acc: 0.9983 - output_3_acc: 0.9957
Epoch 409/1000
3000/3000 [==============================] - 0s 45us/step - loss: 0.1460 - output_0_loss: 0.0430 - output_1_loss: 0.0424 - output_2_loss: 0.0326 - output_3_loss: 0.0281 - output_0_acc: 0.9967 - output_1_acc: 0.9960 - output_2_acc: 0.9997 - output_3_acc: 0.9990
Epoch 410/1000
3000/3000 [==============================] - 0s 45us/step - loss: 0.1484 - output_0_loss: 0.0417 - output_1_loss: 0.0397 - output_2_loss: 0.0349 - output_3_loss: 0.0322 - o

3000/3000 [==============================] - 0s 40us/step - loss: 0.1158 - output_0_loss: 0.0317 - output_1_loss: 0.0299 - output_2_loss: 0.0283 - output_3_loss: 0.0259 - output_0_acc: 0.9997 - output_1_acc: 0.9980 - output_2_acc: 0.9970 - output_3_acc: 0.9977
Epoch 437/1000
3000/3000 [==============================] - 0s 41us/step - loss: 0.1251 - output_0_loss: 0.0314 - output_1_loss: 0.0341 - output_2_loss: 0.0327 - output_3_loss: 0.0270 - output_0_acc: 0.9977 - output_1_acc: 0.9980 - output_2_acc: 0.9983 - output_3_acc: 0.9967
Epoch 438/1000
3000/3000 [==============================] - 0s 42us/step - loss: 0.1116 - output_0_loss: 0.0287 - output_1_loss: 0.0319 - output_2_loss: 0.0263 - output_3_loss: 0.0247 - output_0_acc: 0.9990 - output_1_acc: 0.9977 - output_2_acc: 0.9983 - output_3_acc: 0.9987
Epoch 439/1000
3000/3000 [==============================] - 0s 45us/step - loss: 0.1113 - output_0_loss: 0.0327 - output_1_loss: 0.0316 - output_2_loss: 0.0240 - output_3_loss: 0.0231 - o

3000/3000 [==============================] - 0s 41us/step - loss: 0.0898 - output_0_loss: 0.0238 - output_1_loss: 0.0259 - output_2_loss: 0.0193 - output_3_loss: 0.0208 - output_0_acc: 0.9990 - output_1_acc: 0.9983 - output_2_acc: 0.9980 - output_3_acc: 0.9983
Epoch 466/1000
3000/3000 [==============================] - 0s 41us/step - loss: 0.0982 - output_0_loss: 0.0261 - output_1_loss: 0.0270 - output_2_loss: 0.0286 - output_3_loss: 0.0166 - output_0_acc: 0.9987 - output_1_acc: 0.9970 - output_2_acc: 0.9977 - output_3_acc: 0.9990
Epoch 467/1000
3000/3000 [==============================] - 0s 41us/step - loss: 0.0762 - output_0_loss: 0.0232 - output_1_loss: 0.0226 - output_2_loss: 0.0166 - output_3_loss: 0.0138 - output_0_acc: 0.9997 - output_1_acc: 0.9993 - output_2_acc: 0.9993 - output_3_acc: 1.0000
Epoch 468/1000
3000/3000 [==============================] - 0s 41us/step - loss: 0.0990 - output_0_loss: 0.0267 - output_1_loss: 0.0284 - output_2_loss: 0.0232 - output_3_loss: 0.0206 - o

3000/3000 [==============================] - 0s 45us/step - loss: 0.0726 - output_0_loss: 0.0216 - output_1_loss: 0.0174 - output_2_loss: 0.0196 - output_3_loss: 0.0141 - output_0_acc: 0.9990 - output_1_acc: 0.9997 - output_2_acc: 0.9970 - output_3_acc: 0.9983
Epoch 495/1000
3000/3000 [==============================] - 0s 44us/step - loss: 0.0616 - output_0_loss: 0.0140 - output_1_loss: 0.0187 - output_2_loss: 0.0153 - output_3_loss: 0.0136 - output_0_acc: 0.9997 - output_1_acc: 0.9990 - output_2_acc: 0.9987 - output_3_acc: 0.9997
Epoch 496/1000
3000/3000 [==============================] - 0s 45us/step - loss: 0.0717 - output_0_loss: 0.0215 - output_1_loss: 0.0190 - output_2_loss: 0.0150 - output_3_loss: 0.0162 - output_0_acc: 0.9980 - output_1_acc: 0.9983 - output_2_acc: 0.9993 - output_3_acc: 0.9980
Epoch 497/1000
3000/3000 [==============================] - 0s 45us/step - loss: 0.0669 - output_0_loss: 0.0154 - output_1_loss: 0.0188 - output_2_loss: 0.0186 - output_3_loss: 0.0141 - o

3000/3000 [==============================] - 0s 42us/step - loss: 0.0488 - output_0_loss: 0.0153 - output_1_loss: 0.0130 - output_2_loss: 0.0104 - output_3_loss: 0.0102 - output_0_acc: 0.9987 - output_1_acc: 0.9997 - output_2_acc: 1.0000 - output_3_acc: 1.0000
Epoch 524/1000
3000/3000 [==============================] - 0s 43us/step - loss: 0.0502 - output_0_loss: 0.0143 - output_1_loss: 0.0134 - output_2_loss: 0.0112 - output_3_loss: 0.0113 - output_0_acc: 0.9987 - output_1_acc: 0.9993 - output_2_acc: 1.0000 - output_3_acc: 0.9987
Epoch 525/1000
3000/3000 [==============================] - 0s 41us/step - loss: 0.0562 - output_0_loss: 0.0148 - output_1_loss: 0.0173 - output_2_loss: 0.0155 - output_3_loss: 0.0086 - output_0_acc: 0.9997 - output_1_acc: 0.9993 - output_2_acc: 0.9973 - output_3_acc: 1.0000
Epoch 526/1000
3000/3000 [==============================] - 0s 42us/step - loss: 0.0478 - output_0_loss: 0.0135 - output_1_loss: 0.0125 - output_2_loss: 0.0099 - output_3_loss: 0.0120 - o

3000/3000 [==============================] - 0s 41us/step - loss: 0.0422 - output_0_loss: 0.0120 - output_1_loss: 0.0119 - output_2_loss: 0.0103 - output_3_loss: 0.0080 - output_0_acc: 0.9993 - output_1_acc: 1.0000 - output_2_acc: 1.0000 - output_3_acc: 1.0000
Epoch 553/1000
3000/3000 [==============================] - 0s 41us/step - loss: 0.0383 - output_0_loss: 0.0097 - output_1_loss: 0.0124 - output_2_loss: 0.0094 - output_3_loss: 0.0069 - output_0_acc: 1.0000 - output_1_acc: 0.9987 - output_2_acc: 0.9997 - output_3_acc: 1.0000
Epoch 554/1000
3000/3000 [==============================] - 0s 39us/step - loss: 0.0381 - output_0_loss: 0.0113 - output_1_loss: 0.0077 - output_2_loss: 0.0095 - output_3_loss: 0.0097 - output_0_acc: 0.9990 - output_1_acc: 1.0000 - output_2_acc: 0.9993 - output_3_acc: 0.9997
Epoch 555/1000
3000/3000 [==============================] - 0s 41us/step - loss: 0.0402 - output_0_loss: 0.0111 - output_1_loss: 0.0108 - output_2_loss: 0.0113 - output_3_loss: 0.0070 - o

3000/3000 [==============================] - 0s 44us/step - loss: 0.0317 - output_0_loss: 0.0087 - output_1_loss: 0.0104 - output_2_loss: 0.0074 - output_3_loss: 0.0052 - output_0_acc: 1.0000 - output_1_acc: 0.9993 - output_2_acc: 0.9997 - output_3_acc: 1.0000
Epoch 582/1000
3000/3000 [==============================] - 0s 40us/step - loss: 0.0302 - output_0_loss: 0.0073 - output_1_loss: 0.0078 - output_2_loss: 0.0079 - output_3_loss: 0.0071 - output_0_acc: 1.0000 - output_1_acc: 1.0000 - output_2_acc: 0.9993 - output_3_acc: 0.9993
Epoch 583/1000
3000/3000 [==============================] - 0s 44us/step - loss: 0.0326 - output_0_loss: 0.0103 - output_1_loss: 0.0076 - output_2_loss: 0.0055 - output_3_loss: 0.0092 - output_0_acc: 0.9990 - output_1_acc: 1.0000 - output_2_acc: 1.0000 - output_3_acc: 0.9990
Epoch 584/1000
3000/3000 [==============================] - 0s 42us/step - loss: 0.0305 - output_0_loss: 0.0064 - output_1_loss: 0.0101 - output_2_loss: 0.0088 - output_3_loss: 0.0051 - o

3000/3000 [==============================] - 0s 44us/step - loss: 0.0258 - output_0_loss: 0.0067 - output_1_loss: 0.0060 - output_2_loss: 0.0078 - output_3_loss: 0.0054 - output_0_acc: 1.0000 - output_1_acc: 0.9993 - output_2_acc: 0.9997 - output_3_acc: 1.0000
Epoch 611/1000
3000/3000 [==============================] - 0s 45us/step - loss: 0.0211 - output_0_loss: 0.0072 - output_1_loss: 0.0060 - output_2_loss: 0.0048 - output_3_loss: 0.0031 - output_0_acc: 1.0000 - output_1_acc: 1.0000 - output_2_acc: 1.0000 - output_3_acc: 1.0000
Epoch 612/1000
3000/3000 [==============================] - 0s 39us/step - loss: 0.0223 - output_0_loss: 0.0043 - output_1_loss: 0.0071 - output_2_loss: 0.0051 - output_3_loss: 0.0059 - output_0_acc: 1.0000 - output_1_acc: 0.9993 - output_2_acc: 1.0000 - output_3_acc: 1.0000
Epoch 613/1000
3000/3000 [==============================] - 0s 41us/step - loss: 0.0244 - output_0_loss: 0.0086 - output_1_loss: 0.0070 - output_2_loss: 0.0054 - output_3_loss: 0.0034 - o

3000/3000 [==============================] - 0s 42us/step - loss: 0.0179 - output_0_loss: 0.0045 - output_1_loss: 0.0037 - output_2_loss: 0.0053 - output_3_loss: 0.0043 - output_0_acc: 1.0000 - output_1_acc: 1.0000 - output_2_acc: 1.0000 - output_3_acc: 1.0000
Epoch 640/1000
3000/3000 [==============================] - 0s 43us/step - loss: 0.0193 - output_0_loss: 0.0054 - output_1_loss: 0.0065 - output_2_loss: 0.0039 - output_3_loss: 0.0034 - output_0_acc: 1.0000 - output_1_acc: 1.0000 - output_2_acc: 1.0000 - output_3_acc: 0.9997
Epoch 641/1000
3000/3000 [==============================] - 0s 45us/step - loss: 0.0199 - output_0_loss: 0.0054 - output_1_loss: 0.0054 - output_2_loss: 0.0055 - output_3_loss: 0.0036 - output_0_acc: 1.0000 - output_1_acc: 1.0000 - output_2_acc: 1.0000 - output_3_acc: 1.0000
Epoch 642/1000
3000/3000 [==============================] - 0s 42us/step - loss: 0.0180 - output_0_loss: 0.0059 - output_1_loss: 0.0042 - output_2_loss: 0.0042 - output_3_loss: 0.0038 - o

3000/3000 [==============================] - 0s 42us/step - loss: 0.0128 - output_0_loss: 0.0032 - output_1_loss: 0.0032 - output_2_loss: 0.0028 - output_3_loss: 0.0036 - output_0_acc: 1.0000 - output_1_acc: 1.0000 - output_2_acc: 1.0000 - output_3_acc: 1.0000
Epoch 669/1000
3000/3000 [==============================] - 0s 44us/step - loss: 0.0138 - output_0_loss: 0.0034 - output_1_loss: 0.0044 - output_2_loss: 0.0032 - output_3_loss: 0.0028 - output_0_acc: 1.0000 - output_1_acc: 1.0000 - output_2_acc: 1.0000 - output_3_acc: 1.0000
Epoch 670/1000
3000/3000 [==============================] - 0s 43us/step - loss: 0.0146 - output_0_loss: 0.0033 - output_1_loss: 0.0032 - output_2_loss: 0.0050 - output_3_loss: 0.0031 - output_0_acc: 1.0000 - output_1_acc: 1.0000 - output_2_acc: 1.0000 - output_3_acc: 1.0000
Epoch 671/1000
3000/3000 [==============================] - 0s 43us/step - loss: 0.0158 - output_0_loss: 0.0045 - output_1_loss: 0.0046 - output_2_loss: 0.0024 - output_3_loss: 0.0043 - o

3000/3000 [==============================] - 0s 43us/step - loss: 0.0132 - output_0_loss: 0.0040 - output_1_loss: 0.0034 - output_2_loss: 0.0023 - output_3_loss: 0.0034 - output_0_acc: 1.0000 - output_1_acc: 1.0000 - output_2_acc: 1.0000 - output_3_acc: 1.0000
Epoch 698/1000
3000/3000 [==============================] - 0s 43us/step - loss: 0.0107 - output_0_loss: 0.0021 - output_1_loss: 0.0025 - output_2_loss: 0.0033 - output_3_loss: 0.0028 - output_0_acc: 1.0000 - output_1_acc: 1.0000 - output_2_acc: 1.0000 - output_3_acc: 1.0000
Epoch 699/1000
3000/3000 [==============================] - 0s 42us/step - loss: 0.0122 - output_0_loss: 0.0040 - output_1_loss: 0.0037 - output_2_loss: 0.0029 - output_3_loss: 0.0017 - output_0_acc: 0.9997 - output_1_acc: 1.0000 - output_2_acc: 1.0000 - output_3_acc: 1.0000
Epoch 700/1000
3000/3000 [==============================] - 0s 42us/step - loss: 0.0101 - output_0_loss: 0.0019 - output_1_loss: 0.0024 - output_2_loss: 0.0037 - output_3_loss: 0.0022 - o

3000/3000 [==============================] - 0s 42us/step - loss: 0.0086 - output_0_loss: 0.0018 - output_1_loss: 0.0028 - output_2_loss: 0.0023 - output_3_loss: 0.0018 - output_0_acc: 1.0000 - output_1_acc: 1.0000 - output_2_acc: 1.0000 - output_3_acc: 1.0000
Epoch 727/1000
3000/3000 [==============================] - 0s 42us/step - loss: 0.0104 - output_0_loss: 0.0036 - output_1_loss: 0.0026 - output_2_loss: 0.0018 - output_3_loss: 0.0023 - output_0_acc: 1.0000 - output_1_acc: 1.0000 - output_2_acc: 1.0000 - output_3_acc: 1.0000  
Epoch 728/1000
3000/3000 [==============================] - 0s 43us/step - loss: 0.0073 - output_0_loss: 0.0015 - output_1_loss: 0.0025 - output_2_loss: 0.0022 - output_3_loss: 0.0011 - output_0_acc: 1.0000 - output_1_acc: 1.0000 - output_2_acc: 1.0000 - output_3_acc: 1.0000
Epoch 729/1000
3000/3000 [==============================] - 0s 42us/step - loss: 0.0095 - output_0_loss: 0.0027 - output_1_loss: 0.0018 - output_2_loss: 0.0030 - output_3_loss: 0.0019 -

3000/3000 [==============================] - 0s 42us/step - loss: 0.0073 - output_0_loss: 0.0017 - output_1_loss: 0.0020 - output_2_loss: 0.0019 - output_3_loss: 0.0016 - output_0_acc: 1.0000 - output_1_acc: 1.0000 - output_2_acc: 1.0000 - output_3_acc: 1.0000 
Epoch 756/1000
3000/3000 [==============================] - 0s 42us/step - loss: 0.0087 - output_0_loss: 0.0020 - output_1_loss: 0.0027 - output_2_loss: 0.0028 - output_3_loss: 0.0011 - output_0_acc: 1.0000 - output_1_acc: 1.0000 - output_2_acc: 0.9997 - output_3_acc: 1.0000         
Epoch 757/1000
3000/3000 [==============================] - 0s 47us/step - loss: 0.0082 - output_0_loss: 0.0027 - output_1_loss: 0.0014 - output_2_loss: 0.0014 - output_3_loss: 0.0028 - output_0_acc: 1.0000 - output_1_acc: 1.0000 - output_2_acc: 1.0000 - output_3_acc: 0.9997     
Epoch 758/1000
3000/3000 [==============================] - 0s 45us/step - loss: 0.0074 - output_0_loss: 0.0017 - output_1_loss: 0.0022 - output_2_loss: 0.0020 - output_3_l

3000/3000 [==============================] - 0s 46us/step - loss: 0.0072 - output_0_loss: 0.0018 - output_1_loss: 0.0011 - output_2_loss: 0.0017 - output_3_loss: 0.0026 - output_0_acc: 1.0000 - output_1_acc: 1.0000 - output_2_acc: 1.0000 - output_3_acc: 0.9993      
Epoch 785/1000
3000/3000 [==============================] - 0s 45us/step - loss: 0.0053 - output_0_loss: 0.0015 - output_1_loss: 0.0023 - output_2_loss: 6.3695e-04 - output_3_loss: 8.5529e-04 - output_0_acc: 1.0000 - output_1_acc: 0.9997 - output_2_acc: 1.0000 - output_3_acc: 1.0000
Epoch 786/1000
3000/3000 [==============================] - 0s 45us/step - loss: 0.0063 - output_0_loss: 0.0013 - output_1_loss: 0.0014 - output_2_loss: 0.0022 - output_3_loss: 0.0015 - output_0_acc: 1.0000 - output_1_acc: 1.0000 - output_2_acc: 1.0000 - output_3_acc: 1.0000         
Epoch 787/1000
3000/3000 [==============================] - 0s 41us/step - loss: 0.0053 - output_0_loss: 0.0012 - output_1_loss: 0.0019 - output_2_loss: 6.5302e-04 

3000/3000 [==============================] - 0s 44us/step - loss: 0.0041 - output_0_loss: 0.0016 - output_1_loss: 0.0011 - output_2_loss: 7.1650e-04 - output_3_loss: 6.4552e-04 - output_0_acc: 1.0000 - output_1_acc: 1.0000 - output_2_acc: 1.0000 - output_3_acc: 1.0000
Epoch 814/1000
3000/3000 [==============================] - 0s 44us/step - loss: 0.0052 - output_0_loss: 0.0010 - output_1_loss: 0.0017 - output_2_loss: 0.0010 - output_3_loss: 0.0015 - output_0_acc: 1.0000 - output_1_acc: 1.0000 - output_2_acc: 1.0000 - output_3_acc: 1.0000         
Epoch 815/1000
3000/3000 [==============================] - 0s 46us/step - loss: 0.0041 - output_0_loss: 9.2627e-04 - output_1_loss: 0.0010 - output_2_loss: 0.0014 - output_3_loss: 7.4928e-04 - output_0_acc: 1.0000 - output_1_acc: 1.0000 - output_2_acc: 1.0000 - output_3_acc: 1.0000
Epoch 816/1000
3000/3000 [==============================] - 0s 43us/step - loss: 0.0056 - output_0_loss: 0.0018 - output_1_loss: 0.0012 - output_2_loss: 9.9714e-0

3000/3000 [==============================] - 0s 39us/step - loss: 0.0035 - output_0_loss: 8.0785e-04 - output_1_loss: 9.7896e-04 - output_2_loss: 6.8784e-04 - output_3_loss: 0.0010 - output_0_acc: 1.0000 - output_1_acc: 1.0000 - output_2_acc: 1.0000 - output_3_acc: 1.0000
Epoch 842/1000
3000/3000 [==============================] - 0s 42us/step - loss: 0.0044 - output_0_loss: 9.3141e-04 - output_1_loss: 0.0012 - output_2_loss: 0.0016 - output_3_loss: 6.0089e-04 - output_0_acc: 1.0000 - output_1_acc: 1.0000 - output_2_acc: 1.0000 - output_3_acc: 1.0000
Epoch 843/1000
3000/3000 [==============================] - 0s 39us/step - loss: 0.0032 - output_0_loss: 0.0012 - output_1_loss: 7.5394e-04 - output_2_loss: 5.6250e-04 - output_3_loss: 6.6582e-04 - output_0_acc: 1.0000 - output_1_acc: 1.0000 - output_2_acc: 1.0000 - output_3_acc: 1.0000
Epoch 844/1000
3000/3000 [==============================] - 0s 40us/step - loss: 0.0031 - output_0_loss: 7.0447e-04 - output_1_loss: 9.4842e-04 - output_2_

3000/3000 [==============================] - 0s 42us/step - loss: 0.0035 - output_0_loss: 9.2114e-04 - output_1_loss: 9.1563e-04 - output_2_loss: 6.8600e-04 - output_3_loss: 9.3790e-04 - output_0_acc: 1.0000 - output_1_acc: 1.0000 - output_2_acc: 1.0000 - output_3_acc: 1.0000
Epoch 870/1000
3000/3000 [==============================] - 0s 44us/step - loss: 0.0032 - output_0_loss: 4.3364e-04 - output_1_loss: 7.8974e-04 - output_2_loss: 9.7115e-04 - output_3_loss: 0.0010 - output_0_acc: 1.0000 - output_1_acc: 1.0000 - output_2_acc: 1.0000 - output_3_acc: 1.0000
Epoch 871/1000
3000/3000 [==============================] - 0s 46us/step - loss: 0.0033 - output_0_loss: 0.0012 - output_1_loss: 8.7850e-04 - output_2_loss: 5.4267e-04 - output_3_loss: 6.0730e-04 - output_0_acc: 1.0000 - output_1_acc: 1.0000 - output_2_acc: 1.0000 - output_3_acc: 1.0000
Epoch 872/1000
3000/3000 [==============================] - 0s 44us/step - loss: 0.0027 - output_0_loss: 5.5386e-04 - output_1_loss: 7.8232e-04 - o

3000/3000 [==============================] - 0s 40us/step - loss: 0.0020 - output_0_loss: 3.9054e-04 - output_1_loss: 5.7959e-04 - output_2_loss: 5.5040e-04 - output_3_loss: 5.2240e-04 - output_0_acc: 1.0000 - output_1_acc: 1.0000 - output_2_acc: 1.0000 - output_3_acc: 1.0000
Epoch 898/1000
3000/3000 [==============================] - 0s 39us/step - loss: 0.0030 - output_0_loss: 8.5359e-04 - output_1_loss: 6.7576e-04 - output_2_loss: 3.8184e-04 - output_3_loss: 0.0011 - output_0_acc: 1.0000 - output_1_acc: 1.0000 - output_2_acc: 1.0000 - output_3_acc: 1.0000
Epoch 899/1000
3000/3000 [==============================] - 0s 40us/step - loss: 0.0020 - output_0_loss: 3.4433e-04 - output_1_loss: 5.8205e-04 - output_2_loss: 6.0388e-04 - output_3_loss: 5.0242e-04 - output_0_acc: 1.0000 - output_1_acc: 1.0000 - output_2_acc: 1.0000 - output_3_acc: 1.0000
Epoch 900/1000
3000/3000 [==============================] - 0s 40us/step - loss: 0.0024 - output_0_loss: 9.7191e-04 - output_1_loss: 4.3187e-04

3000/3000 [==============================] - 0s 43us/step - loss: 0.0016 - output_0_loss: 3.1869e-04 - output_1_loss: 3.7962e-04 - output_2_loss: 5.0391e-04 - output_3_loss: 4.0087e-04 - output_0_acc: 1.0000 - output_1_acc: 1.0000 - output_2_acc: 1.0000 - output_3_acc: 1.0000
Epoch 926/1000
3000/3000 [==============================] - 0s 42us/step - loss: 0.0023 - output_0_loss: 4.6964e-04 - output_1_loss: 9.5509e-04 - output_2_loss: 3.5103e-04 - output_3_loss: 5.3663e-04 - output_0_acc: 1.0000 - output_1_acc: 1.0000 - output_2_acc: 1.0000 - output_3_acc: 1.0000
Epoch 927/1000
3000/3000 [==============================] - 0s 42us/step - loss: 0.0018 - output_0_loss: 6.9354e-04 - output_1_loss: 3.9547e-04 - output_2_loss: 4.6965e-04 - output_3_loss: 2.1999e-04 - output_0_acc: 1.0000 - output_1_acc: 1.0000 - output_2_acc: 1.0000 - output_3_acc: 1.0000
Epoch 928/1000
3000/3000 [==============================] - 0s 44us/step - loss: 0.0019 - output_0_loss: 5.4506e-04 - output_1_loss: 3.0394

3000/3000 [==============================] - 0s 41us/step - loss: 0.0011 - output_0_loss: 2.1370e-04 - output_1_loss: 3.7161e-04 - output_2_loss: 2.5387e-04 - output_3_loss: 2.7394e-04 - output_0_acc: 1.0000 - output_1_acc: 1.0000 - output_2_acc: 1.0000 - output_3_acc: 1.0000
Epoch 954/1000
3000/3000 [==============================] - 0s 42us/step - loss: 0.0016 - output_0_loss: 5.0114e-04 - output_1_loss: 4.2281e-04 - output_2_loss: 5.2092e-04 - output_3_loss: 2.0276e-04 - output_0_acc: 1.0000 - output_1_acc: 1.0000 - output_2_acc: 1.0000 - output_3_acc: 1.0000
Epoch 955/1000
3000/3000 [==============================] - 0s 40us/step - loss: 0.0018 - output_0_loss: 3.3105e-04 - output_1_loss: 6.9187e-04 - output_2_loss: 2.9592e-04 - output_3_loss: 4.6627e-04 - output_0_acc: 1.0000 - output_1_acc: 1.0000 - output_2_acc: 1.0000 - output_3_acc: 1.0000
Epoch 956/1000
3000/3000 [==============================] - 0s 41us/step - loss: 0.0013 - output_0_loss: 6.1264e-04 - output_1_loss: 2.8775

3000/3000 [==============================] - 0s 40us/step - loss: 0.0012 - output_0_loss: 1.4972e-04 - output_1_loss: 4.2005e-04 - output_2_loss: 4.2907e-04 - output_3_loss: 1.6572e-04 - output_0_acc: 1.0000 - output_1_acc: 1.0000 - output_2_acc: 1.0000 - output_3_acc: 1.0000
Epoch 982/1000
3000/3000 [==============================] - 0s 43us/step - loss: 0.0011 - output_0_loss: 4.8185e-04 - output_1_loss: 1.4330e-04 - output_2_loss: 1.6315e-04 - output_3_loss: 2.6707e-04 - output_0_acc: 1.0000 - output_1_acc: 1.0000 - output_2_acc: 1.0000 - output_3_acc: 1.0000
Epoch 983/1000
3000/3000 [==============================] - 0s 43us/step - loss: 0.0016 - output_0_loss: 3.0861e-04 - output_1_loss: 5.9614e-04 - output_2_loss: 4.4337e-04 - output_3_loss: 2.4998e-04 - output_0_acc: 1.0000 - output_1_acc: 1.0000 - output_2_acc: 1.0000 - output_3_acc: 1.0000
Epoch 984/1000
3000/3000 [==============================] - 0s 42us/step - loss: 9.5990e-04 - output_0_loss: 2.7595e-04 - output_1_loss: 1.

In [13]:
def print_readable_prediction(prediction, nb_words):
    
    words = [''] * nb_words
    
    c_i = 0
    for char_prediction in prediction:

        s_i = 0
        for sample_char_prediction in char_prediction:

            i_letter = 0
            best_value = -float('inf')
            best_letter = -1
            for letter_prediction in sample_char_prediction:
                if letter_prediction > best_value:
                    best_value = letter_prediction
                    best_letter = i_letter
                i_letter += 1
            words[s_i] += str(best_letter)
            words[s_i] += '-'
            s_i += 1
        c_i += 1
    print(words)

In [14]:
nb_words = 2

x_test = create_inputs(nb_words, nb_chars, nb_letters)
display_x(x_test)
print("x_test=\n", x_test)

x_test_n  = scaler.transform(x_test)
print("x_test_mean=\n", x_test_n)
print('-->')

prediction = model.predict(x_test_n)
#print(prediction)
print('prediction')
print_readable_prediction(prediction, nb_words)

print('check prediction')
y_test = encrypt(x_test, nb_words, nb_chars)
print("y_test=\n", y_test)

['ilul', 'xqvn']
x_test=
 [[105 108 117 108]
 [120 113 118 110]]
x_test_mean=
 [[-0.63063583 -0.172304    0.98722364 -0.19880777]
 [ 1.40805759  0.48769599  1.12110867  0.07210902]]
-->
prediction
['8-11-20-11-', '23-16-21-13-']
check prediction
y_test=
 [[ 8 11 20 11]
 [23 16 21 13]]


/usr/local/lib/python3.6/dist-packages/sklearn/utils/validation.py:595: DataConversionWarning: Data with input dtype int64 was converted to float64 by StandardScaler.
  warnings.warn(msg, DataConversionWarning)
