In [1]:
from __future__ import print_function, division
from builtins import range, input
import tensorflow as tf
from tensorflow.keras.models import Model
from tensorflow.keras.layers import Input, LSTM, GRU
import numpy as np
import matplotlib.pyplot as plt

In [2]:
print(tf.__version__)

2.0.0


In [3]:
T = 8 # sequence length
D = 2 # input dimensionality
M = 3 # hidden layer size

In [4]:
# random single sentence of (T=8) words (of) vectors (of Dimensionality 2)
X = np.random.randn(1, T, D)

In [5]:
def lstm(return_sequences):
    input_ = Input(shape=(T, D))
    rnn = LSTM(M, return_state=True, return_sequences=return_sequences)
    x = rnn(input_)
    
    model = Model(inputs=input_, outputs=x)
    o, h, c = model.predict(X)
    print("o:", o) # output state
    print("h:", h) # hidden state
    print("c:", c) # cell state

In [6]:
def gru(return_sequences=False):
    input_ = Input(shape=(T, D))
    rnn = GRU(M, return_state=True, return_sequences=return_sequences)
    x = rnn(input_)
    
    model = Model(inputs=input_, outputs=x)
    o, h = model.predict(X)
    print("o:", o)
    print("h:", h)

In [7]:
X

array([[[-1.73394974, -0.71413386],
        [ 1.02563316,  1.98625841],
        [ 0.81784878, -0.62754348],
        [-0.15946988, -0.61045713],
        [-1.26686826, -1.13625935],
        [ 0.32856318, -1.41968732],
        [ 0.41914402, -0.17297239],
        [-0.78343575,  0.59002825]]])

In [8]:
print('lstm(return_sequences=False)')
lstm(return_sequences=False)
# should see that 'h'idden is actually the 'o'utput

lstm(return_sequences=False)
o: [[-0.14669798 -0.03754031 -0.1142506 ]]
h: [[-0.14669798 -0.03754031 -0.1142506 ]]
c: [[-0.24777451 -0.07086815 -0.17149094]]


In [9]:
print('lstm(return_sequences=True)')
lstm(return_sequences=True)
# same as before, except that sequence lenght is of asize T (8)
# see that 'h' is the same as last element of 'o' 
# thus, 'h' and 'c' represent the last state of LSTM (ie last timestep)

lstm(return_sequences=True)
o: [[[-0.02360118  0.04548688 -0.09549893]
  [-0.05679564  0.16474661  0.07663298]
  [ 0.04283164  0.02309753 -0.0168109 ]
  [ 0.08899377 -0.04162308 -0.09969093]
  [ 0.12392537 -0.08250352 -0.25178382]
  [ 0.3021257  -0.16928403 -0.24798277]
  [ 0.25735804 -0.16895261 -0.2131155 ]
  [ 0.09332512 -0.01386919 -0.10768051]]]
h: [[ 0.09332512 -0.01386919 -0.10768051]]
c: [[ 0.23692676 -0.02546185 -0.21116292]]


In [10]:
print('gru(return_sequences=False)')
gru(return_sequences=True)

gru(return_sequences=False)
o: [[[-0.25822088 -0.11663557  0.06088384]
  [ 0.3210874   0.27232215  0.10672334]
  [ 0.14221     0.26673096 -0.15772323]
  [-0.02901417  0.12582669 -0.17018807]
  [-0.2828023   0.00854827 -0.14201334]
  [-0.3624295   0.09569412 -0.3328796 ]
  [-0.14104734  0.12406164 -0.2657905 ]
  [-0.01471875 -0.0693494  -0.03338622]]]
h: [[-0.01471875 -0.0693494  -0.03338622]]


In [11]:
print('gru(return_sequences=True)')
gru(return_sequences=True)

gru(return_sequences=True)
o: [[[-0.65682447  0.28109878 -0.19301726]
  [-0.56963    -0.39338362  0.46534318]
  [-0.15502834 -0.5010007   0.22817338]
  [-0.12507793 -0.25302842  0.02947593]
  [-0.5473185   0.07235198 -0.18831843]
  [ 0.0081118  -0.09516468 -0.3689533 ]
  [ 0.1446636  -0.16865529 -0.14482236]
  [-0.27880386  0.16408935 -0.09538844]]]
h: [[-0.27880386  0.16408935 -0.09538844]]
